ALTER TABLE `dispatchers` ADD INDEX(`B_USER_ID`);
ALTER TABLE `dispatchers` ADD FOREIGN KEY (`B_USER_ID`) REFERENCES `b_user`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `dispatchers` ADD INDEX(`OBJECT_ID`);
ALTER TABLE `dispatchers` ADD FOREIGN KEY (`OBJECT_ID`) REFERENCES `objects`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;